# Generated by Django 5.2.3 on 2025-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_settings_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
