# Generated by Django 5.2.3 on 2025-06-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice_question_settings_delete_pollresult_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
